Feature/airlock streaming
CSCfi/sda-filesystem pull request #151
Opened 2023-08-11 12:00 UTC by emm1R

Enable streaming when uploading files with airlock by sending the checksum in the manifest file.

Other changes:
- public-key argument https://gitlab.ci.csc.fi/sds-dev/sd-desktop/sda-filesystem/-/issues/12
- Update segment container name https://gitlab.ci.csc.fi/sds-dev/sd-desktop/sda-filesystem/-/issues/8

2023-08-15 13:17 UTC, blankdots requested changes
i think it might be cleaner if we don't place the public keys for test as files, we can use vars for test see https://github.com/neicnordic/crypt4gh/blob/master/keys/keys_test.go


missing changelog and version bump

2023-08-15 13:17 UTC, blankdots commented on cmd/airlock/main.go
> +		"[-public-key=publicKeyFile] [-quiet] username container filename")
we need to add this info to main readme

2023-08-25 08:54 UTC, emm1R commented
> i think it might be cleaner if we don't place the public keys for test as files, we can use vars for test see https://github.com/neicnordic/crypt4gh/blob/master/keys/keys_test.go
> 
> missing changelog and version bump

But then the tests won't work

2023-08-25 10:09 UTC, blankdots commented
waiting to be tested

2023-09-04 08:26 UTC, teemukataja commented
- [x] tested airlock proxy export works with multiple public keys
- [ ] manifest file to be tested, pending airlock api update

2024-04-15 10:55 UTC, closed without merging